name: app_a_o_c
description: Application pour l'Association des Oléiculteurs de Callian.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  path_provider: ^2.0.11
  csv: ^6.0.0
  intl: ^0.19.0
  file_picker: ^9.0.2
  qr_flutter: ^4.0.0
  table_calendar: ^3.1.3
  package_info_plus: ^8.3.0


  english_words: ^4.0.0
  provider: ^6.0.0
  
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/icon/iconeAppOlive512x512.png"
  android: true
  ios: true
  windows:
    generate: true
  macos:    
    generate: true
  web:
    generate: true

flutter:
  uses-material-design: true
  assets:
    - assets/icon/iconeAppOlive512x512.png